liveloveapp/hashbrown

.env.test, package-lock.json, package.json, www/src/app/app.config.ts, www/src/app/components/EnterpriseProducts.ts, www/src/app/components/Hero.ts, www/src/app/env.d.ts, www/src/app/pages/enterprise/index.page.ts, www/src/app/services/FirebaseService.ts
- Updated enterprise products component that is reused throughout.
- Draft of enterprise landing page with contact form.
- Adding firebase + firestore for contact form.
- Using LLA firebase project.
closes #45
=> Enterprise landing page

packages/core/src/schema/internal/base.ts, packages/core/src/schema/internal/toJsonSchema.ts, packages/core/src/streaming-json-parser/test/client.ts, packages/core/src/utils/exposeComponent.ts, samples/smart-home/client/src/app/shared/predictions.component.ts
Fixes https://github.com/liveloveapp/hashbrown/issues/31
=> Remove description from anyOf

packages/core/src/streaming-json-parser/parser.ts, packages/core/src/streaming-json-parser/test/client.ts, packages/core/src/streaming-json-parser/test/server.ts
Fixes https://github.com/liveloveapp/hashbrown/issues/70
=> Support schemas with outer element arrays

samples/smart-home/client/src/app/app.component.ts, samples/smart-home/client/src/app/features/chat/chat-panel.component.ts, samples/smart-home/client/src/app/features/lights/light-form.component.ts, samples/smart-home/client/src/app/features/lights/lights.component.ts, samples/smart-home/client/src/app/features/scenes/scene-form-dialog/scene-form-dialog.component.ts, samples/smart-home/client/src/app/features/scenes/scenes.component.ts, samples/smart-home/client/src/app/models/scheduled-scene.model.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/actions/index.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/actions/scheduled-scenes-api.actions.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/actions/scheduled-scenes-page.actions.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/schedule-scene-form-dialog/schedule-scene-form-dialog.component.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/scheduled-scenes.component.ts
Scheduled scenes is still WIP, though, and will be improved in a follow-on PR.
=> Tweak various things in Angular example to improve UX. 

package-lock.json, samples/smart-home/client/src/app/app.config.ts, samples/smart-home/client/src/app/features/scenes/effects/scenes-api.effects.ts, samples/smart-home/client/src/app/features/scenes/scenes.component.ts, samples/smart-home/client/src/app/models/scheduled-scene.model.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/effects/scheduled-scenes-api.effects.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/schedule-scene-form-dialog/schedule-scene-form-dialog.component.ts, samples/smart-home/client/src/app/pages/scheduled-scenes/scheduled-scenes.component.ts, samples/smart-home/client/src/app/services/smart-home.service.ts, samples/smart-home/client/src/app/store/index.ts, samples/smart-home/client/src/app/store/scheduled-scenes.reducer.ts
Fixes https://github.com/liveloveapp/hashbrown/issues/52
=> Angular example flesh out scheduled scenes

packages/angular/src/chat-resource.fn.ts, packages/angular/src/completion-resource.fn.ts, packages/angular/src/structured-chat-resource.fn.ts, samples/smart-home/client/src/app/app.config.ts, samples/smart-home/client/src/app/shared/predictions.component.ts
Execute provided hashbrown middleware in Angular's injection context.
=> fix: provider injector

packages/LICENSE, packages/core/src/schema/base.ts, packages/core/src/streaming-json-parser/parser.ts
- add root LICENSE file with MIT license and credits
- add attribution to top of appropriate files
closes #86
=> chore: licenses and credits

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
- add PR template for GitHub
- update root README
- add contribution doc
=> chore: readme and contribution docs, PR template

samples/smart-home/client/src/app/features/chat/chat-panel.component.ts, samples/smart-home/client/src/app/features/lights/light-form.component.ts, samples/smart-home/client/src/app/features/lights/lights.component.ts, samples/smart-home/server/src/main.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> chore(samples): Clean up the Angular sample

www/index.html
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Closes #164
```
[ ] Yes
[x] No
```
=> feat(www): analytics

www/src/app/components/Providers.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> feat(www): Add Intro to Hashbrown video

www/index.html, www/src/app/components/Providers.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> fix: vimeo video player

www/src/app/pages/docs/angular/platform/google.md, www/src/app/pages/docs/angular/platform/openai.md, www/src/app/pages/docs/angular/platform/writer.md, www/src/app/pages/docs/angular/start/quick.md, www/src/app/pages/docs/react/platform/google.md, www/src/app/pages/docs/react/platform/openai.md, www/src/app/pages/docs/react/platform/writer.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> docs(www): Update the documentation for consuming providers

CHANGELOG.md, packages/angular/package.json, packages/azure/package.json, packages/core/package.json, packages/google/package.json, packages/openai/package.json, packages/react/package.json, packages/tool-javascript/package.json, packages/writer/package.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> chore(release): publish 0.1.0

package.json, www/src/app/pages/docs/angular/concept/structured-output.md, www/src/app/pages/docs/angular/start/quick.md, www/src/examples/angular/__base/package-lock.json, www/src/examples/angular/__base/package.json, www/src/examples/angular/__base/src/main.ts, www/src/examples/angular/chat/src/app/components/chat.component.ts, www/src/examples/angular/function-calling/src/app/components/chat.component.ts, www/src/examples/angular/structured-output/src/app/components/chat.component.ts, www/src/examples/angular/ui-chat/src/app/components/chat.component.ts, www/src/examples/react/chat/src/app/App.tsx
```
[x] Bugfix
[ ] Feature
```
Fixes Angular examples.
```
[ ] Yes
[x] No
```
=> Fix examples

www/src/app/pages/docs/angular/concept/functions.md
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
Closes #
```
[ ] Yes
[X] No
```
=> Fixing typo in docs

www/src/app/components/LongIntroVideo.ts, www/src/app/components/Providers.ts, www/src/app/components/QuickIntroVideo.ts, www/src/app/pages/(home).page.ts, www/src/app/pages/docs/angular/start/quick.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
Add 5 highlights video to home page and put the demo video in a section. Also, add demo video to Angular quick start page.
```
[ ] Yes
[x] No
```
=> Video on homepage

samples/smart-home/client/src/app/shared/predictions.component.ts, www/src/app/components/DocsHeader.ts, www/src/app/components/ExamplesHeader.ts, www/src/app/components/Hero.ts, www/src/app/components/ldp/LdpTour.ts, www/src/app/pages/docs/angular/concept/components.md, www/src/app/pages/docs/react/concept/components.md, www/src/app/services/MenuService.ts
```
[ ] Bugfix
[ ] Feature
```
- Updated homepage hero
- Generative UI doc page
- New documentation for exposing components in React and Angular
```
[ ] Yes
[x] No
```
=> feat(www): hero and docs

www/src/app/components/Footer.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
Added `Built with AnalogJS` to the footer of the documentation site.
```
[ ] Yes
[x] No
```
=> docs: add Built with AnalogJS to footer

package-lock.json, package.json, packages/angular/src/utils/create-tool-javascript.fn.ts, samples/finance/client/project.json, samples/finance/client/src/app/chart/ChartPage.ts, samples/finance/client/src/app/chart/Chat.ts, samples/finance/client/src/app/chart/CodeLoader.ts, samples/finance/client/src/app/chart/CodeModal.ts, samples/finance/client/src/app/chart/CommerceData.ts, samples/finance/client/src/index.html
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> samples: Improve quality of the finance chart demo

packages/core/src/runtime/create-runtime-impl.ts, packages/core/src/runtime/proxies/intl.ts, packages/core/src/runtime/proxies/intl/DateTimeFormat.ts, samples/finance/client/src/app/app.config.ts, samples/finance/client/src/app/chart/AiToastNotification.ts, samples/finance/client/src/app/chart/ChartExamples.ts, samples/finance/client/src/app/chart/ChartPage.ts, samples/finance/client/src/app/chart/Chat.ts, samples/finance/client/src/app/chart/CodeLoader.ts, samples/finance/client/src/app/chart/CommerceData.ts, samples/finance/client/src/app/chart/Ingredients.ts, samples/finance/client/src/server.ts, samples/finance/client/src/server/ingredients.ts, samples/finance/client/src/styles.scss, samples/smart-home/client/src/app/features/lights/light-form.component.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> samples: Improve theming and quality of the Finance sample

packages/angular/tsconfig.json, samples/finance/client/src/app/app.config.ts, samples/finance/client/src/app/chart/AiToastNotification.ts, samples/finance/client/src/app/chart/ChartExamples.ts, samples/finance/client/src/app/chart/ChartPage.ts, samples/finance/client/src/app/chart/Chat.ts, samples/finance/client/src/app/chart/schema/chartSchema.ts, samples/finance/client/src/app/chart/schema/ingredientSchema.ts, samples/finance/client/src/app/chart/schema/queryIngredientsSchema.ts, samples/finance/client/src/server.ts, samples/finance/client/tsconfig.json, samples/smart-home/client/tsconfig.json, tsconfig.base.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> styles(finance): Continue to improve the Finance example

packages/core/src/effects/generate-message.effects.spec.ts, packages/core/src/effects/generate-message.effects.ts
```
[X] Bugfix
[ ] Feature
```
Closes #252
```
[ ] Yes
[ ] No
```
=> fix(core): Handle situations where no choices are generated

packages/angular/src/resources/chat-resource.fn.ts, packages/angular/src/resources/completion-resource.fn.ts, packages/angular/src/resources/structured-chat-resource.fn.ts, packages/angular/src/utils/signals.ts, packages/azure/src/integration.spec.ts, packages/core/src/actions/internal.actions.ts, packages/core/src/effects/generate-message.effects.ts, packages/core/src/hashbrown.ts, packages/core/src/public_api.ts, packages/core/src/reducers/index.ts, packages/core/src/reducers/tools.reducer.ts, packages/core/src/utils/deep-equal.ts, packages/core/src/utils/index.ts, packages/core/src/utils/micro-ngrx.spec.ts, packages/core/src/utils/micro-ngrx.ts, packages/google/src/integration.spec.ts, packages/openai/src/integration.spec.ts, packages/react/src/hooks/use-chat.spec.tsx, packages/react/src/hooks/use-chat.tsx, packages/react/src/hooks/use-completion.tsx, packages/react/src/hooks/use-hashbrown-signal.ts, packages/react/src/hooks/use-structured-chat.spec.tsx, packages/react/src/hooks/use-structured-chat.tsx, packages/react/src/hooks/use-structured-completion.tsx, packages/react/src/hooks/use-ui-chat.tsx, packages/writer/src/integration.spec.ts, samples/smart-home/client-react/src/app/shared/RichChatPanel.tsx
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> refactor(react): expose state via useSyncExternalStore

packages/react/src/hooks/use-runtime-function.tsx, packages/react/src/hooks/use-runtime.tsx, packages/react/src/hooks/use-tool-javascript.tsx, packages/react/src/index.ts, packages/react/src/public-api.ts, samples/smart-home/client-react/src/app/shared/RichChatPanel.tsx
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> feat(react): Add JavaScript runtime hooks

www/src/content/blog/2025-07-16-hashbrown-v-0-2-0.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> docs: Clean up v0.2.0 blog post

packages/core/package.json, packages/core/project.json, packages/react/package.json, packages/react/project.json
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
Update core and react package configurations for release.
```
[ ] Yes
[x] No
```
=> chore(core,react): package and build configurations

packages/core/package.json, packages/core/project.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> fix(samples): Get sample server running again

README.md, package-lock.json, package.json, packages/angular/src/utils/create-tool.fn.ts, packages/core/src/effects/tools.effects.ts, packages/core/src/models/internal.models.ts, packages/core/src/models/internal_helpers.ts, packages/core/src/models/view.models.ts, packages/core/src/schema/base.ts, packages/core/src/schema/public_api.ts, samples/mcp/client/project.json, samples/mcp/client/proxy.conf.json, samples/mcp/client/public/favicon.svg, samples/mcp/client/src/app/app.config.server.ts, samples/mcp/client/src/app/app.config.ts, samples/mcp/client/src/app/app.routes.server.ts, samples/mcp/client/src/app/app.routes.ts, samples/mcp/client/src/app/app.ts, samples/mcp/client/src/app/projects/project-chat.ts, samples/mcp/client/src/app/projects/projects.ts, samples/mcp/client/src/index.html, samples/mcp/client/src/main.server.ts, samples/mcp/client/src/main.ts, samples/mcp/client/src/node.ts, samples/mcp/client/src/server.ts, samples/mcp/client/src/server/ingredients.ts, samples/mcp/client/src/styles.scss, samples/mcp/client/tsconfig.app.json, samples/mcp/client/tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> samples: Scaffolds out the Angular MCP sample

README.md, package.json, packages/angular/src/resources/ui-chat-resource.fn.ts, www/src/app/components/Footer.ts
=> fix(www): take year in copyright dinamically

packages/core/src/index.ts, packages/core/src/prompt/__snapshots__/prompt.spec.ts.snap, packages/core/src/prompt/prompt.spec.ts, packages/core/src/prompt/prompt.ts, packages/core/src/prompt/types.ts, packages/core/src/public_api.ts, packages/core/src/schema/base.ts, packages/core/src/schema/to-streaming.spec.ts, packages/core/src/ui/expose-component.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> feat(core): Add prompt template literal tag function

packages/angular/src/resources/ui-chat-resource.fn.ts, packages/react/src/hooks/use-ui-chat.tsx, samples/smart-home/angular/src/app/chat/chat-panel.ts, samples/smart-home/react/src/app/shared/RichChatPanel.tsx
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> feat(angular,react): Add support for the prompt function in UI chat

packages/angular/src/components/render-message.component.ts, packages/angular/src/utils/ui-chat.helpers.ts, packages/core/src/prompt/__snapshots__/prompt.spec.ts.snap, packages/core/src/prompt/prompt.spec.ts, packages/core/src/prompt/prompt.ts, packages/core/src/ui/expose-component.ts, packages/react/src/hooks/use-ui-chat.tsx
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> refactor(core,angular,react): Envelope props in $props

package-lock.json, www/index.html, www/src/app/components/CodeExample.ts, www/src/app/components/CodeExampleGroup.ts, www/src/app/components/DocsMenu.ts, www/src/app/components/Footer.ts, www/src/app/components/Header.ts, www/src/app/components/LiveLoveAppButton.ts, www/src/app/components/PostPreview.ts, www/src/app/components/Products.ts, www/src/app/components/home/Adapters.ts, www/src/app/components/ldp/LdpCompletions.ts, www/src/app/components/ldp/LpdNaturalLanguage.ts, www/src/app/components/ldp/LpdWindow.ts, www/src/app/pages/blog/index.page.ts, www/src/app/pages/contact-us/index.page.ts, www/src/app/pages/docs/angular/concept/schema.md, www/src/app/pages/docs/angular/concept/streaming.md, www/src/app/pages/docs/react/concept/components.md, www/src/app/pages/docs/react/concept/streaming.md
Fixes www docs fonts and content updates
```
[ ] Bugfix
[ ] Feature
```
=> feat(www): fredoka font and content updates

www/src/app/pages/workshops.page.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> WWW: Update workshop dates

www/src/app/components/DocsMenu.ts, www/src/app/pages/docs/angular/concept/components.md, www/src/app/pages/docs/angular/concept/schema.md, www/src/app/pages/docs/angular/platform/ollama.md, www/src/app/pages/docs/react/concept/components.md, www/src/app/pages/docs/react/concept/schema.md, www/src/app/pages/docs/react/platform/ollama.md, www/src/app/pages/docs/react/recipes/remote-mcp.md
```
[ ] Bugfix
[ ] Feature
```
Related #309 
- Add documentation for `prompt` tagged template literal
- Add documentation for Ollama adapter
- Update documentation for React remote MCP
```
[ ] Yes
[x] No
```
=> feat(www): prompt tagged template literal, ollama, remote mcp with react

www/src/app/components/DocsMenu.ts, www/src/app/components/home/Samples.ts, www/src/app/pages/docs/angular/recipes/ui-chatbot.md, www/src/app/pages/docs/react/recipes/ui-chatbot.md, www/src/tools/create-rough-draft.ts, www/src/tools/review-docs.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> docs(www): Add recipes for building UI chatbots

packages/ollama/package.json
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> chore(ollama): Fix package.json dependencies

www/src/app/components/Footer.ts, www/src/app/components/home/Samples.ts, www/src/app/pages/contact-us/index.page.ts, www/src/app/pages/docs/angular/platform/ollama.md, www/src/app/pages/docs/react/platform/ollama.md, www/src/app/pages/workshops.page.ts, www/src/content/blog/2025-09-05-hashbrown-v-0-3-0.md, www/src/content/workshops/mcp-fundamentals.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> feat(www): mcp fundamentals date

www/src/app/pages/workshops.page.ts, www/src/content/workshops/mcp-fundamentals.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> fix: set workshop to inactive

README.md, packages/angular/README.md, packages/azure/README.md, packages/core/README.md, packages/google/README.md, packages/ollama/README.md, packages/openai/README.md, packages/react/README.md, packages/writer/README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> chore: update readme

www/src/app/pages/docs/angular/platform/custom.md, www/src/app/pages/docs/react/platform/custom.md, www/src/app/pages/docs/react/start/platforms.md
```
[ ] Bugfix
[ ] Feature
```
Hashbrown supports multiple adapters, but there is currently no documentation explaining how users can create custom adapter providers.
Closes #328
* Added comprehensive documentation for creating custom adapter providers
* Created detailed guides for **React** and **Angular** frameworks
* Included full TypeScript code examples
* Covered:
* Core interfaces (`CompletionCreateParams`, `Frame`, etc.)
* Message transformation
* Tool calling & …
=> docs(www): add comprehensive guide for creating custom adapter providers

www/src/app/pages/docs/angular/start/quick.md, www/src/app/pages/docs/react/start/quick.md
update docs quickstart:
- fixed adapter links for React and Angular
- ensured React quickstart links navigate to React-specific versions
- added link to ollama
fixes #340
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
- Missing Ollama adapter link in Docs Quickstart for React & Angular
- Adapter links in Docs Quickstart for React direct to Angular [i.e to https://hashbrown.dev/docs/angular/platform/ollama]
Closes # 340
- Add Ollama adapter link in Docs Quickstart for React & Angular
- …
=> docs(react,angular): update quickstart adapter links and add ollama

README.md
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> Righteous Readme Rework 

samples/smart-home/angular/src/app/scenes/add-scene-form.ts, samples/smart-home/angular/src/app/scenes/rrule-parser.ts, samples/smart-home/angular/src/app/scenes/rrule-visualization/rrule-detail-section.ts, samples/smart-home/angular/src/app/scenes/rrule-visualization/rrule-types.ts, samples/smart-home/angular/src/app/scenes/rrule-visualization/rrule-utils.ts, samples/smart-home/angular/src/app/scenes/rrule-visualization/rrule-visualization.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> samples: RRULE visualizer

samples/smart-home/angular/src/app/lights/add-light-form.ts, samples/smart-home/angular/src/app/scenes/add-scene-form.ts, samples/smart-home/angular/src/app/suggestions/suggestor.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> samples: Return to action architecture for suggestions

samples/finance/netlify/tools/generate-ingredients.ts, samples/finance/server/tools/generate-ingredients.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> fix(samples): roll back faker data

package-lock.json, www/src/app/pages/docs/react/recipes/ui-chatbot.md, www/src/app/pages/docs/react/start/sample.md
```
[ ] Bugfix
[ ] Feature
```
Currently, Step 1 of the [UI Chatbot React recipe](https://hashbrown.dev/docs/react/recipes/ui-chatbot) has a .ts file extension for the smart-home.ts file. Since this file exports a React component, this file should have a .tsx extension.
Also, the last heading on the [React Samples page](https://hashbrown.dev/docs/react/start/sample) says *Startthe Application* when it should say *Start the Application*.
Line 44 of the …
=> docs(react): recipes file extension change and samples typo fix.

samples/finance/angular/src/app/chart/ChartPage.ts, samples/finance/angular/src/app/chart/Welcome.ts, samples/finance/angular/src/app/squircle.ts, samples/smart-home/angular/src/app/dashboard/dashboard.ts, samples/smart-home/angular/src/app/dashboard/welcome.ts, www/src/app/components/home/Hero.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> feat(www): sample app overlay

www/netlify.toml, www/project.json, www/src/tools/generate-llms.mjs
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> fix(www): generate llms after build

www/analog/src/app/components/GitHubStarButton.ts, www/analog/src/app/components/Header.ts, www/analog/src/app/components/SearchOverlay.ts, www/analog/src/app/icons/FileCode.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> feat(www): header search

www/analog/src/app/components/Header.ts, www/analog/src/app/components/Squircle.ts
```
[ ] Bugfix
[ ] Feature
```
Closes #
```
[ ] Yes
[ ] No
```
=> fix(www): squircle fallback
